#! /bin/sh
# Script to start parse_ibnetdiscover within loop
###
# chkconfig: 235 99 99
# description: parsing ibnetdiscover-output
# and dumps it into qnib
###

case "$1" in
  start)
        echo -n "Starting qnib-ibnetdis"
        #To run it as root:
        /root/QNIB/serverfiles/usr/local/bin/parse_ibnetdiscover.py \
            --ibsim --force-uptopo \
            --graphviz-cmd=twopi --loop --delay 15 &
        echo "."
        ;;
  stop)
        echo -n "Stopping qnib-ibnetdis"
        #To run it as root:
        killall /root/QNIB/serverfiles/usr/local/bin/parse_ibnetdiscover.py
        echo "."
        ;;

  *)
        echo "Usage: /sbin/service qnib-ibnetdis" {start|stop}"
        exit 1
esac

exit 0