#! /bin/sh
###
# chkconfig: 235 99 99
# description: Starts rrd_update and rrd_graph within a loop
###

case "$1" in
  start)
        echo -n "Starting qnib-netgraph"
        #To run it as root:
        /root/QNIB/serverfiles/usr/local/bin/create_netgraph.py \
            -g plain --loop $
        /root/QNIB/serverfiles/usr/local/bin/create_netgraph.py \
            -g perf --loop  &
        echo "."
        ;;
  stop)
        echo -n "Stopping qnib-netgraph"
        #To run it as root:
        /usr/bin/pkill -f 'python /root/QNIB/serverfiles/usr/local/bin/create_netgraph.py'
        echo "."
        ;;

  *)
        echo "Usage: /sbin/service qnib-netgraph {start|stop}"
        exit 1
esac

exit 0
